---
repo-name: peripherals-ms-sharepoint
categories:
- Project Management
- Collaboration
display-name: Microsoft SharePoint
manufacturer: Microsoft
product: SharePoint
description: Microsoft SharePoint is a browser-based collaboration and document management platform from Microsoft.
